-- MySQL Script generated by MySQL Workbench
-- mié 13 nov 2019 09:35:01 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering



-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 ;
USE mydb ;

-- -----------------------------------------------------
-- Table mydb.Producto
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.Producto ;

CREATE TABLE IF NOT EXISTS mydb.Producto (
  Cód_Prod INT NOT NULL,
  Precio INT NOT NULL,
  Stock INT GENERATED ALWAYS AS (),
  Nombre VARCHAR(45) NULL,
  PRIMARY KEY (Cód_Prod))



-- -----------------------------------------------------
-- Table mydb.Vivero
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.Vivero ;

CREATE TABLE IF NOT EXISTS mydb.Vivero (
  Coordenadas FLOAT NOT NULL,
  Localidad VARCHAR(45) NULL,
  Nombre VARCHAR(45) NULL,
  PRIMARY KEY (Coordenadas))



-- -----------------------------------------------------
-- Table mydb.Zona
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.Zona ;

CREATE TABLE IF NOT EXISTS mydb.Zona (
  Coordenadas FLOAT NOT NULL,
  Nombre VARCHAR(45) NOT NULL,
  PRIMARY KEY (Coordenadas, Nombre),
  CONSTRAINT Coordenadas
    FOREIGN KEY (Coordenadas)
    REFERENCES mydb.Vivero (Coordenadas)
    ON DELETE CASCADE
    ON UPDATE CASCADE)



-- -----------------------------------------------------
-- Table mydb.Cliente
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.Cliente ;

CREATE TABLE IF NOT EXISTS mydb.Cliente (
  Bonificación FLOAT NULL,
  Total_mensual FLOAT NULL,
  Nombre VARCHAR(45) NULL,
  DNI VARCHAR(45) NOT NULL,
  PRIMARY KEY (DNI))



-- -----------------------------------------------------
-- Table mydb.Empleado
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.Empleado ;

CREATE TABLE IF NOT EXISTS mydb.Empleado (
  Sueldo FLOAT NULL,
  CSS VARCHAR(45) NULL,
  Antiguedad INT NULL DEFAULT 0,
  Nombre_Zona VARCHAR(45) NOT NULL,
  Coordenadas_Zona FLOAT NOT NULL,
  Fecha_inicio DATE NOT NULL,
  Fecha_fin DATE NULL,
  DNI VARCHAR(45) NOT NULL,
  Ventas INT NOT NULL,
  PRIMARY KEY (Nombre_Zona, Coordenadas_Zona, Fecha_inicio, DNI, Ventas),
  INDEX zona_idx (Nombre_Zona ASC, Coordenadas_Zona ASC),
  CONSTRAINT zona
    FOREIGN KEY (Nombre_Zona , Coordenadas_Zona)
    REFERENCES mydb.Zona (Nombre , Coordenadas)
    ON DELETE CASCADE
    ON UPDATE CASCADE)



-- -----------------------------------------------------
-- Table mydb.Producto_Cliente
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.Producto_Cliente ;

CREATE TABLE IF NOT EXISTS mydb.Producto_Cliente (
  Cód_Prod INT NOT NULL,
  DNI_C VARCHAR(45) NOT NULL,
  DNI_E VARCHAR(45) NOT NULL,
  Fecha_ DATE NOT NULL,
  Cantidad INT NULL,
  PRIMARY KEY (Cód_Prod, DNI_C, DNI_E, Fecha_),
  INDEX Empleado_idx (DNI_E ASC),
  CONSTRAINT Cliente
    FOREIGN KEY (DNI_E)
    REFERENCES mydb.Cliente (DNI)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT Producto
    FOREIGN KEY (Cód_Prod)
    REFERENCES mydb.Producto (Cód_Prod)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT Empleado
    FOREIGN KEY (DNI_E)
    REFERENCES mydb.Empleado (DNI)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table mydb.Producto_Zona
-- -----------------------------------------------------
DROP TABLE IF EXISTS mydb.Producto_Zona ;

CREATE TABLE IF NOT EXISTS mydb.Producto_Zona (
  Cód_prod INT NOT NULL,
  Nombre VARCHAR(45) NOT NULL,
  Coordenadas FLOAT NOT NULL,
  Cantidad INT NULL,
  PRIMARY KEY (Cód_prod, Coordenadas, Nombre),
  INDEX Zona_idx (Nombre ASC, Coordenadas ASC),
  CONSTRAINT Producto
    FOREIGN KEY (Cód_prod)
    REFERENCES mydb.Producto (Cód_Prod)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT Zona
    FOREIGN KEY (Nombre , Coordenadas)
    REFERENCES mydb.Zona (Nombre , Coordenadas)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

